Stattek/WareHelper

src/Driver.java, src/database/Category.java, src/database/Item.java
Adds basic implementations of basic objects:
- Category
- Item
These are in progress. This is a test for pull request structure and process.
=> Add Basic Starting Implementations

src/database/Identifiable.java, src/database/RecordType.java
This is a basic implementation of the Enum and the Interface we had on our class diagaram
=> Add interface Identifiable and RecordType Enum

src/Driver.java
Loads the jar file for the oracle connector before running.
=> Fix running the program.

src/Driver.java
Allow choosing whether to use a local database.
=> Add global variable for Local vs. Online database.

TODO.md, src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/StorageCrud.java
Adding in-progress reads to the database.
=> Add In-Progress reads.

src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/items/Bundle.java, src/database/items/Category.java, src/database/items/ConvertableObject.java, src/database/items/DateInfo.java, src/database/items/EconomyInfo.java, src/database/items/Item.java, src/database/items/Preference.java
Fix up missing attributes.
- Make read use a `Map` instead of a `List`.
- Add getters/setters.
=> Fix up reads

src/Controller.java, src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/StorageCrud.java, src/database/items/Category.java
Added implementation for create method for Storage along with the create category implementation
=> Add crud features and create category

src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/StorageCrud.java, src/database/items/Item.java
-  added bundle ID to Item class with getters and setters
- added the delete method to Storage
- added delete bundle method
=> Delete Bundle  and updates to Item class

src/database/MySqlCrud.java, src/database/StorageCrud.java
implement createItem method, providing the itemStorage.create method with the data (ID's) and keys for the item. Update StorageCrud accordingly.
=> Jack branch (updating createItem)

src/Driver.java, src/database/MySqlCrud.java, src/database/items/Bundle.java, src/database/items/Category.java, src/database/items/ConvertableObject.java, src/database/items/DateInfo.java, src/database/items/EconomyInfo.java, src/database/items/Item.java, src/database/items/ObjectService.java, src/database/items/Preference.java
Implements the creates for the ObjectService class.
- Fix Item getters & setters.
- Enable gson pretty printing for JSON output.
- Finished implementation of #8.
=> Implement object service

src/Driver.java, src/database/MySql.java, src/database/Storage.java
Moves array outside of loop.
- Fixes method name in Storage.
=> Fix use case array.

TODO.md, src/Controller.java, src/database/items/Item.java, src/database/items/ObjectService.java
Adds description to Item.
- Update TODO.md.
=> Add description

src/Controller.java, src/Driver.java, src/InputValidator.java, src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/StorageCrud.java
Implements Search by Item Name (#28).
- Move conversion to JSON into the Controller.
- Add new helper functions for the database.
- Add basic input validation.
=> Add search by name

src/Controller.java, src/Driver.java, src/InputValidator.java, src/database/MySql.java, src/database/MySqlCrud.java, src/database/StorageCrud.java
Create Category, Delete Category, Retrieve Categories (All and By name) are implemented. David had to fix my broken git stuff so he's in here but I did all of this.
=> Implemented category CRUD features

src/Controller.java, src/Driver.java, src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/StorageCrud.java, src/database/items/Bundle.java, src/database/items/ObjectService.java, src/database/reports/ReportGenerator.java, src/database/reports/ReportGeneratorFactory.java
Worked on createItem, harder than I thought. Makes the user provide category label (A), Item name (Jeans), and description. Auto generates date, generates SKU by pulling item id from MySql and combining it with category, gives user options to add price, number of items, and more. Tries to find category ID given the category label, otherwise if no valid category it currently fails.
=> Implement Create Item.

src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java
Basic update functionality in MySQL class
=> Add Database Update Operation.

TODO.md, src/Controller.java, src/Driver.java, src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/StorageCrud.java
Changed category create to match updated logic with object service and changed driver front end to match new logic. Additionally implemented sort by name along with stubs for other sorts while cleaning up the retrieve inventory user menu.
=> Category fixes, sort by name and driver improvements

TODO.md, src/Controller.java, src/Driver.java, src/database/MySql.java, src/database/MySqlCrud.java, src/database/Storage.java, src/database/StorageCrud.java, src/database/items/Bundle.java, src/database/items/Category.java, src/database/items/DateInfo.java, src/database/items/EconomyInfo.java, src/database/items/Item.java, src/database/items/ObjectService.java, src/database/items/OuterObject.java, src/database/items/Preference.java
Adds functionality to Retrieve and Delete Bundles.
- Add ability to perform joins on the database.
- Adds ability to retrieve bundles.
- Adds ability to delete bundles.
- Removes a bunch of hardcoded values referencing table columns or table names.
- Clean up Driver.
- Updated database design for cascading upon deletes.
=> Retrieve and Delete Bundles

src/Controller.java, src/database/items/Bundle.java, src/database/items/Category.java, src/database/items/ConvertableObject.java, src/database/items/DateInfo.java, src/database/items/EconomyInfo.java, src/database/items/Item.java, src/database/items/ObjectService.java, src/database/items/OuterObject.java, src/database/items/Preference.java
Adds new helper methods to allow for getting more information about a database object (such as required values to create, or the list of keys without the ID).
- Update Controller to use these new methods.
- Add new methods to ObjectService to allow using these.
=> Add New Helper Methods for ConvertableObject.

src/Controller.java, src/Driver.java
Use case for sort by date and sort by item cost
=> sort code for cost and created date

README.md, TODO.md, src/Driver.java, src/database/MySql.java, src/database/MySqlCrud.java, src/database/items/ObjectService.java, src/database/items/Preference.java, src/user/Controller.java, src/user/InputValidator.java
Allows the database to automatically create tables if they do not exist.
- Fixes some input validation that was missing.
- Update README.md
- Update TODO.md
=> Add Automatic Table Creation and Fixup Input Validation.

src/database/MySqlCrud.java
Adds database transactions to reads.
=> Database Add Read Transactions.

src/tests/SortItemsByCostTest.java
=> sort test update

src/Driver.java, src/tests/RetrieveInventoryTest.java
Fixes various Driver crashes.
- Make test mutex static.
=> Fix crashes

input.csv, src/Driver.java, src/user/Controller.java
Fixed import from csv to not override date values and added test inputs
=> Fixed imports
